# Generated by Django 4.2.6 on 2023-10-21 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
