# Generated by Django 4.2.6 on 2023-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                default="Customers",
                related_name="users_groups",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
