# Generated by Django 4.2.6 on 2023-10-21 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"permissions": []},
        ),
    ]
